workspace(name = "gitactions_test_repo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_googletest",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip"],
    strip_prefix = "googletest-1.14.0",
    sha256 = "991d32fae7b75b3c7f5f7cb560c07ff2b91bde48d5bc734eac080eb8d1fda0e2",
)
