name: シェル実行してCをビルドする

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: シェルスクリプト実行（前段）
        run: ./scripts/test.sh

      - name: ビルドディレクトリ準備
        run: mkdir -p build

      - name: Cコードをビルド（後段）
        run: gcc -o build/hello src/hello.c

      - name: ビルド成果物を実行
        run: ./build/hello
